import { action } from '../../common';

export const types = {
    AUTH_USER: 'User/AUTH_USER',
    AUTH_USER_REQUEST: 'User/AUTH_USER_REQUEST',
    AUTH_USER_SUCCESS: 'User/AUTH_USER_SUCCESS',
    AUTH_USER_FAILED: 'User/AUTH_USER_FAILED',

    FETCH_USER_INFO_REQUEST: 'User/FETCH_USER_INFO_REQUEST',
    FETCH_USER_INFO_SUCCESS: 'User/FETCH_USER_INFO_SUCCESS',
    FETCH_USER_INFO_FAILED: 'User/FETCH_USER_INFO_FAILED',

    REFRESH_TOKEN_API_SUCCESS: 'User/REFRESH_TOKEN_API_SUCCESS',
    FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
    FETCH_USER_PROFILE_REQUEST: 'FETCH_USER_PROFILE_REQUEST',
    FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
    FETCH_USER_PROFILE_FAILURE: 'FETCH_USER_PROFILE_FAILURE',

    SEND_USER_PROFILE: 'SEND_USER_PROFILE',
    SEND_USER_PROFILE_REQUEST: 'SEND_USER_PROFILE_REQUEST',
    SEND_USER_PROFILE_SUCCESS: 'SEND_USER_PROFILE_SUCCESS',
    SEND_USER_PROFILE_FAILURE: 'SEND_USER_PROFILE_FAILURE',

    CHANGE_USER_PASSWORD: 'CHANGE_USER_PASSWORD',
    CHANGE_USER_PASSWORD_REQUEST: 'CHANGE_USER_PASSWORD_REQUEST',
    CHANGE_USER_PASSWORD_SUCCESS: 'CHANGE_USER_PASSWORD_SUCCESS',
    CHANGE_USER_PASSWORD_FAILURE: 'CHANGE_USER_PASSWORD_FAILURE',

    LOAD_ORGANIZATIONS: 'User/LOAD_ORGANIZATIONS',
    LOAD_ORGANIZATIONS_REQUEST: 'User/LOAD_ORGANIZATIONS_REQUEST',
    LOAD_ORGANIZATIONS_SUCCESS: 'User/LOAD_ORGANIZATIONS_SUCCESS',
    LOAD_ORGANIZATIONS_FAILED: 'User/LOAD_ORGANIZATIONS_FAILED',

    LOGOUT_USER: 'LOGOUT_USER',
    REDIRECT_TO_HOME: 'REDIRECT_TO_HOME',
    SET_DEFAULT_ORGANIZATION: 'User/SET_DEFAULT_ORGANIZATION',
    SET_PROFILE_TAB_INDEX: 'User/SET_PROFILE_TAB_INDEX'
};


export const authenticateUser = (data) => action(types.AUTH_USER, { data });
export const getUserProfileDetails = () => action(types.FETCH_USER_PROFILE);

export const sentUserDetails = (userId, data) => action(types.SEND_USER_PROFILE, { userId, data });

export const changePassword = (data) => action(types.CHANGE_USER_PASSWORD, { data });

export const logout = () => action(types.LOGOUT_USER);

export const redirectToHome = () => action(types.REDIRECT_TO_HOME);

export const loadOrganization = () => action(types.LOAD_ORGANIZATIONS);

export const setDefaultOrganization = (data) => action(types.SET_DEFAULT_ORGANIZATION, { data });

export const setTabIndex = (data) => action(types.SET_PROFILE_TAB_INDEX, { data });

